### ISSUE TITLE
Create Initial UML Structure Diagram (discussion version)

### ISSUE THREAD

**Issue by ToddCooper** [HL7/DeviceAlerting#1]
Create an initial PlantUML model for the DeviceAlert and related resources.

**Comment by ToddCooper** [comment]
@ElliotSilver   With the IG file structure now in main, is it OK to add this models folder as well - IOW will it be ignored by the IG Publisher?  Or should we do something ... different?    

NOTE:  We will probably include the graphic in the IG anyway!  That might be the best approach.  Craft the organization and then pull in Javier's latest model that is in the DeviceAlert proposal + we will have an expanded one that is more akin to what would be in the Device Module space, albeit one that is device alerting use cases focused.

**Comment by ElliotSilver** [comment]
Yes, this can be merged as is (although there might be a conflict on the .gitignore file).

If we decide to use the diagrams in the IG, we can move them into a subdirectory of /input

**Comment by ToddCooper** [comment]
This Issue was resolved by #4
